import type { CodeFile, LocalizedText } from "./types";

type CodeFileInput = Omit<CodeFile, "label"> & { label?: string };

const t = (ja: string, zh: string): LocalizedText => ({ ja, zh });
const snippet = (...lines: string[]) => lines.join("\n");

const compactLabel = (path: string) => {
  const [, ...rest] = path.split("/");
  if (rest.length <= 2) {
    return rest.join("/") || path;
  }
  return rest.slice(-2).join("/");
};

const codeFile = ({ label, ...file }: CodeFileInput): CodeFile => ({
  ...file,
  label: label ?? compactLabel(file.path),
});

export const codeFiles: CodeFile[] = [
  codeFile({
    id: "app-main-go",
    path: "app-k8s-go/main.go",
    language: "go",
    code: snippet(
      "package main",
      "",
      'import (',
      '    "fmt"',
      '    "log"',
      '    "math/rand"',
      '    "net"',
      '    "net/http"',
      '    "net/http/pprof"',
      '    "os"',
      '    "strings"',
      '    "time"',
      "",
      '    "app-k8s-go/pkg/metrics"',
      '    "github.com/prometheus/client_golang/prometheus/promhttp"',
      ")",
      "",
      "func index(w http.ResponseWriter, r *http.Request) {",
      '    os.Setenv("VERSION", "v0.0.1")',
      '    version := os.Getenv("VERSION")',
      '    w.Header().Set("VERSION", version)',
      '    fmt.Printf("os version: %s \\n", version)',
      "    for k, v := range r.Header {",
      "        for _, vv := range v {",
      '            fmt.Printf("Header key: %s, Header value: %s \\n", k, v)',
      "            w.Header().Set(k, vv)",
      "        }",
      "    }",
      "    clientip := ClientIP(r)",
      '    log.Printf("Success! Response code: %d", 200)',
      '    log.Printf("Success! clientip: %s", clientip)',
      "}",
      "",
      "func healthz(w http.ResponseWriter, r *http.Request) {",
      '    fmt.Fprintf(w, "working")',
      "}",
      "",
      "func main() {",
      "    metrics.Register()",
      "    mux := http.NewServeMux()",
      '    mux.HandleFunc("/debug/pprof/", pprof.Index)',
      '    mux.HandleFunc("/images", images)',
      '    mux.Handle("/metrics", promhttp.Handler())',
      '    mux.HandleFunc("/healthz", healthz)',
      '    if err := http.ListenAndServe(":8088", mux); err != nil {',
      '        log.Fatalf("start http server failed, error: %s\\n", err.Error())',
      "    }",
      "}",
    ),
    summary: t(
      "Go HTTP サービスの入口です。ヘルスチェック、pprof、Prometheus メトリクスを同じプロセスで公開します。",
      "Go HTTP 服务入口，统一提供健康检查、pprof 和 Prometheus 指标端点。",
    ),
    points: [
      t("/healthz は Kubernetes の liveness/readinessProbe から直接利用できます。", "/healthz 可直接用于 Kubernetes liveness/readinessProbe。"),
      t("/metrics は Prometheus scrape 用のエンドポイントです。", "/metrics 是 Prometheus 抓取应用指标的端点。"),
      t("ClientIP の抽出で Ingress/Proxy 配下のアクセスログ説明に使えます。", "ClientIP 提取逻辑便于说明 Ingress/Proxy 下的访问日志处理。"),
    ],
  }),
  codeFile({
    id: "app-metrics-go",
    path: "app-k8s-go/pkg/metrics/metrics.go",
    language: "go",
    code: snippet(
      "package metrics",
      "",
      'import (',
      '    "fmt"',
      '    "time"',
      "",
      '    "github.com/prometheus/client_golang/prometheus"',
      ")",
      "",
      "func Register() {",
      "    err := prometheus.Register(functionLatency)",
      "    if err != nil {",
      "        fmt.Println(err)",
      "    }",
      "}",
      "",
      "const (",
      '    MetricsNamespace = "appk8sgo"',
      ")",
      "",
      "func NewTimer() *ExecutionTimer {",
      "    return NewExecutionTimer(functionLatency)",
      "}",
      "",
      "var (",
      "    functionLatency = CreateExecutionTimeMetric(MetricsNamespace,",
      '        "Time spent.")',
      ")",
      "",
      "func (t *ExecutionTimer) ObserveTotal() {",
      '    (*t.histo).WithLabelValues("total").Observe(time.Now().Sub(t.start).Seconds())',
      "}",
      "",
      "func CreateExecutionTimeMetric(namespace string, help string) *prometheus.HistogramVec {",
      "    return prometheus.NewHistogramVec(",
      "        prometheus.HistogramOpts{",
      "            Namespace: namespace,",
      '            Name:      "execution_latency_seconds",',
      "            Buckets:   prometheus.ExponentialBuckets(0.001, 2, 15),",
      '        }, []string{"step"},',
      "    )",
      "}",
    ),
    summary: t(
      "Prometheus Histogram によるアプリケーションレイテンシ計測を切り出しています。",
      "将应用延迟统计封装为 Prometheus Histogram 指标。",
    ),
    points: [
      t("namespace を appk8sgo に固定し、Grafana 側の検索性を上げています。", "namespace 固定为 appk8sgo，便于 Grafana 查询。"),
      t("ExponentialBuckets で短時間から長時間までの遅延を観測します。", "使用 ExponentialBuckets 覆盖短延迟到长延迟场景。"),
      t("ExecutionTimer を分離し、処理ステップ別の拡張余地を残しています。", "抽象 ExecutionTimer，为后续分步骤计时留出扩展空间。"),
    ],
  }),
  codeFile({
    id: "app-dockerfile",
    path: "app-k8s-go/Dockerfile",
    language: "dockerfile",
    code: snippet(
      "FROM golang:1.19",
      "",
      'ENV GO111MODULE="on"',
      "",
      "WORKDIR /go/src/app",
      "",
      "COPY . .",
      "",
      "RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o webserver",
      "",
      "FROM alpine:latest",
      "",
      "WORKDIR /root/",
      "",
      "# 从编译阶段复制文件",
      "COPY --from=0 /go/src/app/webserver .",
      "",
      "EXPOSE 8088",
      "",
      "USER 10001:10001",
      'ENTRYPOINT ["./webserver"]',
    ),
    summary: t(
      "Go のビルドステージと Alpine 実行ステージを分けたマルチステージ Dockerfile です。",
      "使用 Go 构建阶段和 Alpine 运行阶段分离的多阶段 Dockerfile。",
    ),
    points: [
      t("CGO を無効化し Linux/amd64 の静的バイナリを作成します。", "关闭 CGO，构建 Linux/amd64 静态二进制。"),
      t("実行イメージを Alpine に絞り、配布サイズを小さくします。", "运行阶段基于 Alpine，降低镜像体积。"),
      t("非 root UID で実行し、コンテナ実行権限を抑えます。", "使用非 root UID 运行，降低容器权限风险。"),
    ],
  }),
  codeFile({
    id: "app-go-mod",
    path: "app-k8s-go/go.mod",
    language: "text",
    code: snippet(
      "module app-k8s-go",
      "",
      "go 1.17",
      "",
      "require github.com/gin-gonic/gin v1.8.2",
      "",
      "require (",
      "    github.com/beorn7/perks v1.0.1 // indirect",
      "    github.com/gin-contrib/sse v0.1.0 // indirect",
      "    github.com/prometheus/client_golang v1.14.0 // indirect",
      "    github.com/prometheus/common v0.37.0 // indirect",
      "    github.com/prometheus/procfs v0.8.0 // indirect",
      "    golang.org/x/net v0.4.0 // indirect",
      "    gopkg.in/yaml.v2 v2.4.0 // indirect",
      ")",
    ),
    summary: t(
      "Go モジュールと Prometheus/Gin 周辺依存を示す依存関係ファイルです。",
      "展示 Go module 与 Prometheus/Gin 相关依赖关系。",
    ),
    points: [
      t("アプリケーション名と Go バージョンを明示しています。", "明确应用 module 名称和 Go 版本。"),
      t("Prometheus client 依存により /metrics 実装と接続します。", "Prometheus client 依赖与 /metrics 实现相对应。"),
      t("主要依存だけを抜粋し、面接時に説明しやすくしています。", "仅展示主要依赖，便于面试时说明。"),
    ],
  }),
  codeFile({
    id: "app-sonar",
    path: "app-k8s-go/sonar-project.properties",
    language: "properties",
    code: snippet(
      "Dsonar.projectKey=app-k8s-go",
      "Dsonar.projectName=app-k8s-go",
      "Dsonar.sources=.",
      "Dsonar.host.url=http://20.191.181.29:9000",
    ),
    summary: t(
      "SonarQube のプロジェクトキー、対象ソース、サーバーを定義する設定です。",
      "SonarQube 项目 key、扫描源目录与服务地址配置。",
    ),
    points: [
      t("Pipeline の CodeScan stage と同じ projectKey を使います。", "与 Pipeline 的 CodeScan stage 使用同一 projectKey。"),
      t("sources=. によりリポジトリ全体をスキャン対象にします。", "sources=. 表示扫描当前仓库源码。"),
      t("品質ゲート説明の根拠ファイルとして提示できます。", "可作为说明质量门禁配置的依据文件。"),
    ],
  }),
  codeFile({
    id: "helm-chart",
    path: "app-k8s-helm-go/Chart.yaml",
    language: "yaml",
    code: snippet(
      "apiVersion: v2",
      "name: app-k8s-helm-go",
      "description: A Helm chart for Kubernetes",
      "type: application",
      "version: 0.1.0",
      'appVersion: "1.16.0"',
    ),
    summary: t(
      "Go アプリケーションを Kubernetes に配布する Helm application chart のメタ情報です。",
      "用于将 Go 应用发布到 Kubernetes 的 Helm application chart 元信息。",
    ),
    points: [
      t("Chart version と appVersion を分けて管理します。", "区分 Chart 版本与应用版本。"),
      t("CI が values.yaml を更新し、この Chart を CD 側で deploy します。", "CI 更新 values.yaml，CD 侧发布该 Chart。"),
      t("Helm package/upgrade の対象になる単位です。", "这是 helm package/upgrade 的发布单元。"),
    ],
  }),
  codeFile({
    id: "helm-values",
    path: "app-k8s-helm-go/values.yaml",
    label: "app values.yaml",
    language: "yaml",
    code: snippet(
      "replicaCount: 5",
      "selectorLabels:",
      "  app: appgo",
      "image:",
      "  repository: ouha2020/kaniko-go-demo",
      "  pullPolicy: IfNotPresent",
      "  tag: '108'",
      "imagePullSecrets:",
      "- name: test-arc-secret",
      "podAnnotations:",
      "  prometheus.io/scrape: 'true'",
      "  prometheus.io/port: '8088'",
      "podSecurityContext:",
      "  seccompProfile:",
      "    type: RuntimeDefault",
      "  runAsUser: 10001",
      "  runAsGroup: 10001",
      "securityContext:",
      "  privileged: false",
      "  allowPrivilegeEscalation: false",
      "  readOnlyRootFilesystem: true",
      "resources:",
      "  limits:",
      "    cpu: 100m",
      "    memory: 30Mi",
      "  requests:",
      "    cpu: 10m",
      "    memory: 15Mi",
      "autoscaling:",
      "  enabled: true",
      "  minReplicas: 2",
      "  maxReplicas: 20",
      "  targetCPUUtilizationPercentage: 50",
      "maxUnavailable: 1",
      "networkPolicy:",
      "  enabled: true",
      "  allowExternal: true",
    ),
    summary: t(
      "イメージ、探針、Prometheus annotation、SecurityContext、HPA、NetworkPolicy を集約した values です。",
      "集中配置镜像、探针、Prometheus annotation、安全上下文、HPA 和 NetworkPolicy。",
    ),
    points: [
      t("Jenkins が image.tag / repository を更新する前提の値構造です。", "values 结构支持 Jenkins 更新 image.tag / repository。"),
      t("Prometheus scrape annotation を Pod に渡します。", "向 Pod 注入 Prometheus scrape annotation。"),
      t("非特権実行、readOnlyRootFilesystem、seccomp を一括管理します。", "统一管理非特权运行、只读根文件系统和 seccomp。"),
    ],
  }),
  codeFile({
    id: "helm-deployment",
    path: "app-k8s-helm-go/templates/deployment.yaml",
    language: "yaml",
    code: snippet(
      "apiVersion: apps/v1",
      "kind: Deployment",
      "metadata:",
      '  name: {{ include "app-k8s-helm-go.fullname" . }}',
      "spec:",
      "  selector:",
      "    matchLabels:",
      '      {{- include "app-k8s-helm-go.selectorLabels" . | nindent 6 }}',
      "  template:",
      "    metadata:",
      "      annotations:",
      "        {{- toYaml . | nindent 8 }}",
      "    spec:",
      "      topologySpreadConstraints:",
      "      - maxSkew: 2",
      "        topologyKey: topology.kubernetes.io/zone",
      "        whenUnsatisfiable: ScheduleAnyway",
      "      - maxSkew: 2",
      "        topologyKey: kubernetes.io/hostname",
      "        whenUnsatisfiable: ScheduleAnyway",
      '      serviceAccountName: {{ include "app-k8s-helm-go.serviceAccountName" . }}',
      "      securityContext:",
      "        {{- toYaml .Values.podSecurityContext | nindent 8 }}",
      "      terminationGracePeriodSeconds: 60",
      "      containers:",
      "        - name: {{ .Chart.Name }}",
      '          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"',
      "          livenessProbe:",
      "            httpGet:",
      "              path: /healthz",
      "              port: 8088",
      "          readinessProbe:",
      "            httpGet:",
      "              path: /healthz",
      "              port: 8088",
      "          lifecycle:",
      "            preStop:",
      '              exec: { command: ["/bin/bash", "-c", "sleep 10"] }',
    ),
    summary: t(
      "Deployment テンプレートで分散配置、探針、優雅な終了、セキュリティ設定をまとめます。",
      "Deployment 模板集中处理分散调度、探活、优雅退出与安全配置。",
    ),
    points: [
      t("topologySpreadConstraints でゾーン/ノードの偏りを抑えます。", "通过 topologySpreadConstraints 降低可用区/节点偏斜。"),
      t("readiness/liveness が app-k8s-go の /healthz と対応します。", "readiness/liveness 与 app-k8s-go 的 /healthz 对应。"),
      t("preStop と terminationGracePeriodSeconds でローリング更新時の切断を緩和します。", "通过 preStop 与 terminationGracePeriodSeconds 缓解滚动更新断流。"),
    ],
  }),
  codeFile({
    id: "helm-service",
    path: "app-k8s-helm-go/templates/service.yaml",
    language: "yaml",
    code: snippet(
      "apiVersion: v1",
      "kind: Service",
      "metadata:",
      '  name: {{ include "app-k8s-helm-go.fullname" . }}',
      "  labels:",
      '    run: {{ include "app-k8s-helm-go.fullname" . }}',
      '    {{- include "app-k8s-helm-go.labels" . | nindent 4 }}',
      "spec:",
      "  type: {{ .Values.service.type }}",
      "  ports:",
      "    - port: {{ .Values.service.port }}",
      "      targetPort: http",
      "      protocol: TCP",
      "      name: http",
      "  selector:",
      '    {{- include "app-k8s-helm-go.selectorLabels" . | nindent 4 }}',
    ),
    summary: t(
      "Deployment の Pod を ClusterIP Service として公開するテンプレートです。",
      "将 Deployment Pod 暴露为 ClusterIP Service 的模板。",
    ),
    points: [
      t("service.port は values.yaml から注入されます。", "service.port 从 values.yaml 注入。"),
      t("selectorLabels を helper に集約し、Deployment と Service の紐付けを安定させます。", "通过 helper 统一 selectorLabels，保证 Deployment 与 Service 绑定一致。"),
      t("Ingress / Istio VirtualService の backend から参照されます。", "被 Ingress / Istio VirtualService 的 backend 引用。"),
    ],
  }),
  codeFile({
    id: "helm-hpa",
    path: "app-k8s-helm-go/templates/hpa.yaml",
    language: "yaml",
    code: snippet(
      "{{- if .Values.autoscaling.enabled }}",
      "apiVersion: autoscaling/v2beta1",
      "kind: HorizontalPodAutoscaler",
      "metadata:",
      '  name: {{ include "app-k8s-helm-go.fullname" . }}',
      "spec:",
      "  scaleTargetRef:",
      "    apiVersion: apps/v1",
      "    kind: Deployment",
      '    name: {{ include "app-k8s-helm-go.fullname" . }}',
      "  minReplicas: {{ .Values.autoscaling.minReplicas }}",
      "  maxReplicas: {{ .Values.autoscaling.maxReplicas }}",
      "  metrics:",
      "    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}",
      "    - type: Resource",
      "      resource:",
      "        name: cpu",
      "        targetAverageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}",
      "    {{- end }}",
      "{{- end }}",
    ),
    summary: t(
      "CPU/Memory 指標に応じて Pod 数を自動調整する HPA テンプレートです。",
      "根据 CPU/Memory 指标自动调整 Pod 数量的 HPA 模板。",
    ),
    points: [
      t("autoscaling.enabled で環境ごとに有効/無効を切り替えられます。", "通过 autoscaling.enabled 按环境启用或关闭。"),
      t("min/max replicas を values 側で管理します。", "min/max replicas 在 values 中管理。"),
      t("Deployment 名を helper から取得し、release 名変更に追従します。", "Deployment 名通过 helper 获取，可跟随 release 名变化。"),
    ],
  }),
  codeFile({
    id: "helm-networkpolicy",
    path: "app-k8s-helm-go/templates/networkpolicy.yaml",
    language: "yaml",
    code: snippet(
      "{{- if .Values.networkPolicy.enabled }}",
      "apiVersion: networking.k8s.io/v1",
      "kind: NetworkPolicy",
      "metadata:",
      '  name: {{ include "app-k8s-helm-go.fullname" . }}',
      "spec:",
      "  podSelector:",
      "    matchLabels:",
      '      {{- include "app-k8s-helm-go.selectorLabels" . | nindent 6 }}',
      "  policyTypes:",
      "    - Ingress",
      "  ingress:",
      "    - ports:",
      "        - port: {{ .Values.service.port }}",
      "      {{- if .Values.networkPolicy.allowExternal }}",
      "      from:",
      "        - podSelector:",
      "            matchLabels:",
      '              run: {{ include "app-k8s-helm-go.fullname" . }}',
      "      {{- end }}",
      "{{- end }}",
    ),
    summary: t(
      "Pod への inbound 通信を service port と許可元に絞る NetworkPolicy です。",
      "将进入 Pod 的流量限制到指定 service port 和允许来源的 NetworkPolicy。",
    ),
    points: [
      t("networkPolicy.enabled で段階的に導入できます。", "通过 networkPolicy.enabled 可分阶段启用。"),
      t("service.port と連動し、ポート変更時の設定漏れを防ぎます。", "与 service.port 联动，减少端口变更遗漏。"),
      t("Pod 間通信の境界を作品内で説明しやすくしています。", "便于在作品中说明 Pod 间通信边界。"),
    ],
  }),
  codeFile({
    id: "helm-pdb",
    path: "app-k8s-helm-go/templates/poddisruptionbudget.yaml",
    language: "yaml",
    code: snippet(
      "{{- if .Values.maxUnavailable }}",
      '{{- if .Capabilities.APIVersions.Has "policy/v1" -}}',
      "apiVersion: policy/v1",
      "{{- else}}",
      "apiVersion: policy/v1beta1",
      "{{- end }}",
      "kind: PodDisruptionBudget",
      "metadata:",
      '  name: "{{ include "app-k8s-helm-go.fullname" . }}-pdb"',
      "spec:",
      "  maxUnavailable: {{ .Values.maxUnavailable }}",
      "  selector:",
      "    matchLabels:",
      '      {{- include "app-k8s-helm-go.selectorLabels" . | nindent 6 }}',
      "{{- end }}",
    ),
    summary: t(
      "メンテナンスや evict 時の同時停止数を制御する PodDisruptionBudget です。",
      "控制维护或驱逐时同时不可用 Pod 数量的 PodDisruptionBudget。",
    ),
    points: [
      t("Kubernetes API version の差異を Capabilities で吸収します。", "通过 Capabilities 兼容不同 Kubernetes API 版本。"),
      t("maxUnavailable を values から変更できます。", "maxUnavailable 可从 values 中调整。"),
      t("HPA/replica と合わせて可用性設計を説明できます。", "可与 HPA/replica 一起说明可用性设计。"),
    ],
  }),
  codeFile({
    id: "helm-ingress",
    path: "app-k8s-helm-go/templates/ingress.yaml",
    language: "yaml",
    code: snippet(
      "{{- if .Values.ingress.enabled -}}",
      '{{- $fullName := include "app-k8s-helm-go.fullname" . -}}',
      "{{- $svcPort := .Values.service.port -}}",
      '{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}',
      "apiVersion: networking.k8s.io/v1",
      "{{- else -}}",
      "apiVersion: extensions/v1beta1",
      "{{- end }}",
      "kind: Ingress",
      "metadata:",
      "  name: {{ $fullName }}",
      "spec:",
      "  rules:",
      "    {{- range .Values.ingress.hosts }}",
      "    - host: {{ .host | quote }}",
      "      http:",
      "        paths:",
      "          {{- range .paths }}",
      "          - path: {{ .path }}",
      "            backend:",
      "              service:",
      "                name: {{ $fullName }}",
      "                port:",
      "                  number: {{ $svcPort }}",
      "          {{- end }}",
      "    {{- end }}",
      "{{- end }}",
    ),
    summary: t(
      "Kubernetes version の違いを考慮して外部 HTTP 入口を生成する Ingress テンプレートです。",
      "根据 Kubernetes 版本生成外部 HTTP 入口的 Ingress 模板。",
    ),
    points: [
      t("semverCompare で networking.k8s.io/v1 と旧 API を切り替えます。", "通过 semverCompare 切换 networking.k8s.io/v1 与旧 API。"),
      t("hosts / paths / tls を values 側で管理します。", "hosts / paths / tls 由 values 管理。"),
      t("Service 名と port をテンプレート変数で一貫させます。", "Service 名与端口通过模板变量保持一致。"),
    ],
  }),
  codeFile({
    id: "helm-istio",
    path: "app-k8s-helm-go/templates/istioGetway.yaml",
    language: "yaml",
    code: snippet(
      "apiVersion: networking.istio.io/v1alpha3",
      "kind: Gateway",
      "metadata:",
      "  name: appgo-gateway",
      "  namespace: appk8sgo",
      "spec:",
      "  selector:",
      "    istio: ingressgateway",
      "  servers:",
      "  - port:",
      "      number: 80",
      "      name: http",
      "      protocol: HTTP",
      "    hosts:",
      '    - "istio.jenkins.com"',
      "---",
      "apiVersion: networking.istio.io/v1alpha3",
      "kind: VirtualService",
      "metadata:",
      "  name: appgo",
      "spec:",
      "  gateways:",
      "  - appgo-gateway",
      "  http:",
      "  - route:",
      "    - destination:",
      "        host: app-k8s-go-app-k8s-helm-go",
      "        port:",
      "          number: 8088",
    ),
    summary: t(
      "Istio Gateway と VirtualService で外部入口から Service への経路を定義します。",
      "用 Istio Gateway 与 VirtualService 定义外部入口到 Service 的路由。",
    ),
    points: [
      t("selector: istio=ingressgateway でメッシュ入口を指定します。", "selector: istio=ingressgateway 指向服务网格入口。"),
      t("Gateway と VirtualService を分離し、ルーティング拡張に備えます。", "拆分 Gateway 与 VirtualService，便于后续扩展路由。"),
      t("Go アプリの 8088 port に明示的に転送します。", "显式转发到 Go 应用的 8088 端口。"),
    ],
  }),
  codeFile({
    id: "jenkins-k8s",
    path: "app-k8s-jenkinslib/k8s.Jenkinsfile",
    language: "groovy",
    code: snippet(
      '@Library("k8slib") _',
      "import devops.*",
      "",
      "def checkout = new Checkout()",
      "def gitcli = new GitLab()",
      "",
      "pipeline {",
      "  agent {",
      "    kubernetes {",
      "      yaml '''",
      "        apiVersion: v1",
      "        kind: Pod",
      "        spec:",
      "          containers:",
      "          - name: git",
      "            image: bitnami/git:2.39.0",
      "          - name: sonar",
      "            image: sonarsource/sonar-scanner-cli:4.8",
      "          - name: go",
      "            image: golang:1.19",
      "          - name: kaniko",
      "            image: gcr.io/kaniko-project/executor:debug",
      "          - name: alpine",
      "            image: ouha2020/alpine:1.0.0",
      "      '''",
      "    }",
      "  }",
      "",
      "  environment {",
      '    DOCKERHUB_USERNAME = "ouha2020"',
      '    APP_NAME = "kaniko-go-demo"',
      '    IMAGE_NAME = "${DOCKERHUB_USERNAME}" + "/" + "${APP_NAME}"',
      '    IMAGE_TAG = "${BUILD_NUMBER}"',
      "  }",
      "",
      "  stages {",
      "    stage('CodeScan') { container('sonar') { sh 'sonar-scanner ...' } }",
      "    stage('Build') { container('go') { sh 'go build -o webserver' } }",
      "    stage('Create Image') {",
      "      container('kaniko') {",
      '        sh "/kaniko/executor --dockerfile $WORKSPACE/app-k8s-go/Dockerfile --context $WORKSPACE/app-k8s-go --destination $IMAGE_NAME:$IMAGE_TAG"',
      "      }",
      "    }",
      "    stage('Update Helm') {",
      '      yamlData.image.tag = "$IMAGE_TAG"',
      '      yamlData.image.repository = "$IMAGE_NAME"',
      '      gitcli.UpdateRepoFile(projectId, "values.yaml", base64Content, "main")',
      "    }",
      "  }",
      "}",
    ),
    summary: t(
      "Kubernetes Agent 上で Git/Sonar/Go/Kaniko/Alpine の役割を分ける Jenkins Pipeline です。",
      "在 Kubernetes Agent 中拆分 Git/Sonar/Go/Kaniko/Alpine 角色的 Jenkins Pipeline。",
    ),
    points: [
      t("Kaniko で Docker daemon なしにイメージをビルドします。", "通过 Kaniko 无需 Docker daemon 构建镜像。"),
      t("Sonar、Build、Image、Helm 更新を stage 化しています。", "将 Sonar、Build、Image、Helm 更新拆分为 stage。"),
      t("Shared Library の GitLab helper で values.yaml を更新します。", "通过 Shared Library 的 GitLab helper 更新 values.yaml。"),
    ],
  }),
  codeFile({
    id: "jenkins-ci",
    path: "app-k8s-jenkinslib/CI.Jenkinsfile",
    language: "groovy",
    code: snippet(
      '@Library("k8slib") _',
      "import devops.*",
      "",
      "def checkout = new Checkout()",
      "def gitcli = new GitLab()",
      "",
      "pipeline {",
      '  agent { label "build" }',
      "  stages {",
      '    stage("Checkout") {',
      "      steps {",
      "        script {",
      '          checkout.GetCode("${env.srcUrl}", "${env.branchName}")',
      "          env.commitID = gitcli.GetCommitID()",
      '          currentBuild.displayName = "${env.commitID}"',
      "        }",
      "      }",
      "    }",
      '    stage("ImagePush") {',
      "      steps {",
      "        script {",
      '          env.registry = "devopsworld.azurecr.io"',
      '          env.version = "${env.branchName}-${env.commitID}"',
      '          env.imageName = "${env.registry}/${env.buName}/${env.serviceName}:${env.version}"',
      '          sh "docker build -t ${env.imageName} . && docker push ${env.imageName}"',
      "        }",
      "      }",
      "    }",
      '    stage("ReleaseFile") {',
      "      steps {",
      "        script {",
      '          fileData = gitcli.GetRepoFile(projectId, "values.yaml", "main")',
      "          yamlData = readYaml text: fileData",
      '          yamlData.image.tag = "${env.version}"',
      "          writeYaml charset: 'UTF-8', file: 'values.yaml', data: yamlData",
      "        }",
      "      }",
      "    }",
      "  }",
      "}",
    ),
    summary: t(
      "Checkout、イメージ push、Release file 更新を分けた CI Pipeline です。",
      "将 Checkout、镜像推送、Release file 更新拆分的 CI Pipeline。",
    ),
    points: [
      t("branch と commitID から image version を作成します。", "由 branch 与 commitID 生成 image version。"),
      t("ACR へ push した image 名を Helm values に反映します。", "将推送到 ACR 的镜像名写回 Helm values。"),
      t("GitLab API helper により release repository を更新します。", "通过 GitLab API helper 更新 release 仓库。"),
    ],
  }),
  codeFile({
    id: "jenkins-cd",
    path: "app-k8s-jenkinslib/CD.Jenkinsfile",
    language: "groovy",
    code: snippet(
      '@Library("k8slib") _',
      "import devops.*",
      "",
      "def gitcli = new GitLab()",
      "def checkout = new Checkout()",
      "",
      "pipeline {",
      '  agent { label "build" }',
      "  options { skipDefaultCheckout true }",
      "  stages {",
      '    stage("HelmCheckout") {',
      "      steps {",
      "        script {",
      '          sh "[ -d ${env.serviceName} ] || mkdir ${env.serviceName}"',
      '          ws("${WORKSPACE}/${env.serviceName}") {',
      '            checkout.GetCode("${env.srcUrl}", "${env.branchName}")',
      "            env.commitID = gitcli.GetCommitID()",
      "          }",
      "        }",
      "      }",
      "    }",
      '    stage("HelmDeploy") {',
      "      steps {",
      "        script {",
      '          env.namespace = "${env.buName}"',
      '          env.appName = "${env.serviceName}"',
      '          sh "helm package ${env.appName}/"',
      '          sh "helm upgrade --install --create-namespace ${env.appName} ./${env.appName}-*.tgz -n ${env.namespace}"',
      '          sh "helm history ${env.appName} -n ${env.namespace}"',
      "        }",
      "      }",
      "    }",
      '    stage("CheckHealth") {',
      '      steps { script { sh "curl http://${env.domainName}/hello" } }',
      "    }",
      "  }",
      "}",
    ),
    summary: t(
      "Helm Chart を取得し、namespace 作成込みで upgrade/install する CD Pipeline です。",
      "拉取 Helm Chart，并带 namespace 创建执行 upgrade/install 的 CD Pipeline。",
    ),
    points: [
      t("CI と分離し、Release repository の Chart をデプロイ対象にします。", "与 CI 分离，以 Release 仓库中的 Chart 作为部署对象。"),
      t("helm history で release 履歴を確認できます。", "通过 helm history 查询 release 历史。"),
      t("CheckHealth stage で公開 domain の疎通を確認します。", "CheckHealth stage 验证公开域名连通性。"),
    ],
  }),
  codeFile({
    id: "jenkins-gitlab-groovy",
    path: "app-k8s-jenkinslib/src/devops/GitLab.groovy",
    language: "groovy",
    code: snippet(
      "package devops",
      "",
      "def HttpReqByHttpRequest(reqType, reqUrl, reqBody) {",
      '    def gitServer = "http://20.191.181.29/api/v4"',
      "    withCredentials([string(credentialsId: '2d3ae0c3-bd9c-4905-bc35-55c3e94ac00d', variable: 'GITLABTOKEN')]) {",
      "        response = httpRequest acceptType: 'APPLICATION_JSON_UTF8',",
      "                              contentType: 'APPLICATION_JSON_UTF8',",
      "                              customHeaders: [[maskValue: false, name: 'PRIVATE-TOKEN', value: \"${GITLABTOKEN}\"]],",
      "                              httpMode: \"${reqType}\",",
      "                              url: \"${gitServer}/${reqUrl}\",",
      "                              requestBody: \"${reqBody}\"",
      "    }",
      "    return response",
      "}",
      "",
      "def UpdateRepoFile(projectId, filePath, fileContent, branchName) {",
      '    apiUrl = "projects/${projectId}/repository/files/${filePath}"',
      '    reqBody = """{"branch": "${branchName}","encoding":"base64", "content": "${fileContent}", "commit_message": "update a new file"}"""',
      "    response = HttpReqByHttpRequest('PUT', apiUrl, reqBody)",
      "}",
      "",
      "def GetCommitID() {",
      '    ID = sh returnStdout: true, script:"git rev-parse HEAD"',
      '    ID = ID - "\\n"',
      "    return ID[0..7]",
      "}",
    ),
    summary: t(
      "Jenkins Shared Library として GitLab API 操作を共通化した Groovy helper です。",
      "作为 Jenkins Shared Library 封装 GitLab API 操作的 Groovy helper。",
    ),
    points: [
      t("values.yaml の create/update を Pipeline から再利用できます。", "Pipeline 可复用 values.yaml create/update 能力。"),
      t("commit short id を build displayName や image tag に使います。", "commit short id 可用于 build displayName 与 image tag。"),
      t("GitLab API 呼び出しを helper に集約し、Jenkinsfile を薄くします。", "将 GitLab API 调用集中到 helper，使 Jenkinsfile 更简洁。"),
    ],
  }),
  codeFile({
    id: "jenkins-checkout-groovy",
    path: "app-k8s-jenkinslib/src/devops/Checkout.groovy",
    language: "groovy",
    code: snippet(
      "package devops",
      "",
      "def GetCode(srcUrl, branchName) {",
      "    checkout([$class: 'GitSCM',",
      "      branches: [[name: branchName]],",
      "      extensions: [],",
      "      userRemoteConfigs: [[",
      "        credentialsId: 'e07d2a6f-a813-40f1-8e72-70877bb1fedf',",
      "        url: srcUrl",
      "      ]]",
      "    ])",
      "}",
    ),
    summary: t(
      "Git checkout 操作を Shared Library に切り出し、CI/CD Pipeline から再利用します。",
      "将 Git checkout 操作抽为 Shared Library，供 CI/CD Pipeline 复用。",
    ),
    points: [
      t("srcUrl と branchName を Pipeline parameter として扱えます。", "srcUrl 与 branchName 可作为 Pipeline 参数传入。"),
      t("Jenkinsfile の checkout 実装を共通化します。", "统一 Jenkinsfile 中的 checkout 实现。"),
      t("CI と CD の両方で同じ取得処理を使えます。", "CI 与 CD 均可使用相同代码拉取逻辑。"),
    ],
  }),
  codeFile({
    id: "aks-values",
    path: "JenkinsOnAKS/values.yaml",
    label: "Jenkins values.yaml",
    language: "yaml",
    code: snippet(
      'projectName: "devops-apps"',
      "storage:",
      "  jenkins:",
      "    storage: 20Gi",
      "",
      "deployment:",
      "  jenkins:",
      "    replicas: 1",
      "    image: jenkins/jenkins:2.375.1-jdk11",
      "    webPort: 8080",
      "    agentPort: 50000",
      "    resources:",
      "      limits:",
      "        cpu: 2",
      "        memory: 4Gi",
      "      requests:",
      "        cpu: 1",
      "        memory: 1Gi",
      "",
      "roles:",
      "  jenkins:",
      "    serviceAccount: sa-jenkins",
      "",
      "route:",
      "  jenkins:",
      "    domainName: jenkins.cicd.com",
    ),
    summary: t(
      "AKS 上に Jenkins を展開する Helm values です。保存領域、Deployment、RBAC、Route を一元管理します。",
      "AKS 上部署 Jenkins 的 Helm values，统一管理存储、Deployment、RBAC 与 Route。",
    ),
    points: [
      t("Jenkins controller と agent port を values で管理します。", "Jenkins controller 与 agent 端口由 values 管理。"),
      t("PVC サイズと resources を環境に合わせて調整できます。", "PVC 容量与 resources 可按环境调整。"),
      t("ServiceAccount と domain を release 時に注入します。", "发布时注入 ServiceAccount 与访问域名。"),
    ],
  }),
  codeFile({
    id: "aks-jenkins-yaml",
    path: "JenkinsOnAKS/jenkins.yaml",
    language: "yaml",
    code: snippet(
      "kind: PersistentVolumeClaim",
      "apiVersion: v1",
      "metadata:",
      "  name: jenkins-pvc-claim",
      "  namespace: jenkins",
      "spec:",
      "  accessModes:",
      "    - ReadWriteOnce",
      "  resources:",
      "    requests:",
      "      storage: 20Gi",
      "---",
      "apiVersion: v1",
      "kind: ServiceAccount",
      "metadata:",
      "  name: jenkins",
      "  namespace: jenkins",
      "---",
      "apiVersion: apps/v1",
      "kind: Deployment",
      "metadata:",
      "  name: jenkins-deployment",
      "  namespace: jenkins",
      "spec:",
      "  replicas: 1",
      "  template:",
      "    metadata:",
      "      labels:",
      "        app: jenkins",
      "    spec:",
      "      containers:",
      "      - name: jenkins",
      "        image: jenkins/jenkins:2.381-jdk11",
      "        ports:",
      "        - containerPort: 8080",
      "        - containerPort: 50000",
      "        volumeMounts:",
      "        - mountPath: /var/jenkins_home",
      "          name: jenkins-strorage",
    ),
    summary: t(
      "Jenkins を AKS に直接適用するためのベース Kubernetes manifest です。",
      "用于将 Jenkins 直接部署到 AKS 的基础 Kubernetes manifest。",
    ),
    points: [
      t("PVC、ServiceAccount、Deployment をまとめて示しています。", "集中展示 PVC、ServiceAccount、Deployment。"),
      t("8080 と 50000 を分け、Web UI と agent 接続を扱います。", "区分 8080 Web UI 与 50000 agent 连接。"),
      t("Helm 化前のベース manifest として説明できます。", "可作为 Helm 化之前的基础 manifest 说明。"),
    ],
  }),
  codeFile({
    id: "aks-deployment",
    path: "JenkinsOnAKS/devops-apps/templates/deployment-jenkins.yaml",
    language: "yaml",
    code: snippet(
      "kind: Deployment",
      "apiVersion: apps/v1",
      "metadata:",
      "  labels:",
      "    devops-app: jenkins",
      '  name: jenkins-{{ required ".Values.projectName" .Values.projectName }}',
      '  namespace: {{ required ".Values.projectName" .Values.projectName }}',
      "spec:",
      '  replicas: {{ required ".Values.deployment.jenkins.replicas" .Values.deployment.jenkins.replicas }}',
      "  selector:",
      "    matchLabels:",
      "      devops-app: jenkins",
      "  template:",
      "    metadata:",
      "      labels:",
      "        devops-app: jenkins",
      "    spec:",
      "      containers:",
      "        - name: jenkins",
      '          image: {{ required ".Values.deployment.jenkins.image" .Values.deployment.jenkins.image }}',
      "          ports:",
      '            - containerPort: {{ required ".Values.deployment.jenkins.webPort" .Values.deployment.jenkins.webPort }}',
      "              name: web",
      '            - containerPort: {{ required ".Values.deployment.jenkins.agentPort" .Values.deployment.jenkins.agentPort }}',
      "              name: agent",
      "          livenessProbe:",
      "            httpGet:",
      "              path: /login",
      '              port: {{ required ".Values.deployment.jenkins.webPort" .Values.deployment.jenkins.webPort }}',
      "          volumeMounts:",
      "            - name: jenkins-home",
      "              mountPath: /var/lib/jenkins",
      "      serviceAccountName: {{ required \".Values.roles.jenkins.serviceAccount\" .Values.roles.jenkins.serviceAccount }}",
    ),
    summary: t(
      "Jenkins controller を Helm template 化した Deployment です。",
      "将 Jenkins controller Helm 模板化的 Deployment。",
    ),
    points: [
      t("required を使い、必須 values の欠落を install 時に検出します。", "使用 required 在 install 时发现必要 values 缺失。"),
      t("/login の probe で Jenkins 起動状態を確認します。", "通过 /login probe 检查 Jenkins 启动状态。"),
      t("ServiceAccount と PVC を values 連携で注入します。", "ServiceAccount 与 PVC 通过 values 联动注入。"),
    ],
  }),
  codeFile({
    id: "aks-pvc",
    path: "JenkinsOnAKS/devops-storage/templates/pvc-apps-jenkins.yaml",
    language: "yaml",
    code: snippet(
      "kind: PersistentVolumeClaim",
      "apiVersion: v1",
      "metadata:",
      '  name: pvc-apps-jenkins-home{{ required ".Values.projectName" .Values.projectName }}',
      '  namespace: {{ required ".Values.projectName" .Values.projectName }}',
      "spec:",
      "  accessModes:",
      "    - ReadWriteOnce",
      "  resources:",
      "    requests:",
      '      storage: {{ required ".Values.storage.jenkins.storage" .Values.storage.jenkins.storage }}',
    ),
    summary: t(
      "Jenkins home を永続化する PVC テンプレートです。",
      "用于持久化 Jenkins home 的 PVC 模板。",
    ),
    points: [
      t("storage サイズを values で切り替えられます。", "storage 容量可通过 values 调整。"),
      t("projectName を namespace/name に反映し、多環境展開に対応します。", "projectName 注入 namespace/name，支持多环境发布。"),
      t("Deployment の volumeMounts と対応しています。", "与 Deployment 中的 volumeMounts 对应。"),
    ],
  }),
  codeFile({
    id: "aks-route",
    path: "JenkinsOnAKS/devops-apps-route/templates/route-jenkins.yaml",
    language: "yaml",
    code: snippet(
      "kind: Service",
      "apiVersion: v1",
      "metadata:",
      "  labels:",
      "    devops-app: jenkins",
      "  name: jenkins-service",
      '  namespace: {{ required ".Values.projectName" .Values.projectName }}',
      "spec:",
      "  type: ClusterIP",
      "  ports:",
      "    - name: web",
      "      protocol: TCP",
      '      port: {{ required ".Values.deployment.jenkins.webPort" .Values.deployment.jenkins.webPort }}',
      "    - name: slave",
      "      protocol: TCP",
      '      port: {{ required ".Values.deployment.jenkins.agentPort" .Values.deployment.jenkins.agentPort }}',
      "  selector:",
      "    devops-app: jenkins",
      "---",
      "apiVersion: networking.k8s.io/v1",
      "kind: Ingress",
      "metadata:",
      "  name: jenkins-ingress",
      "spec:",
      "  rules:",
      '  - host: {{ required ".Values.route.jenkins.domainName" .Values.route.jenkins.domainName }}',
      "    http:",
      "      paths:",
      "      - pathType: Prefix",
      '        path: "/"',
      "        backend:",
      "          service:",
      "            name: jenkins-service",
    ),
    summary: t(
      "Jenkins Web UI と Agent port を Service/Ingress で公開するテンプレートです。",
      "通过 Service/Ingress 暴露 Jenkins Web UI 与 Agent port 的模板。",
    ),
    points: [
      t("web と agent port を同じ Service で管理します。", "web 与 agent port 在同一 Service 中管理。"),
      t("domainName を values から注入し、AKS addon routing と連携します。", "domainName 从 values 注入，并与 AKS addon routing 配合。"),
      t("Jenkins controller Deployment の label selector と一致します。", "与 Jenkins controller Deployment 的 label selector 保持一致。"),
    ],
  }),
  codeFile({
    id: "aks-role",
    path: "JenkinsOnAKS/devops-apps-roles/templates/role-jenkins.yaml",
    language: "yaml",
    code: snippet(
      "apiVersion: v1",
      "kind: ServiceAccount",
      "metadata:",
      "  labels:",
      "    devops-app: jenkins",
      '  name: {{ required ".Values.roles.jenkins.serviceAccount" .Values.roles.jenkins.serviceAccount }}',
      '  namespace: {{ required ".Values.projectName" .Values.projectName }}',
      "---",
      "kind: Role",
      "apiVersion: rbac.authorization.k8s.io/v1",
      "metadata:",
      " name: jenkins",
      ' namespace: {{ required ".Values.projectName" .Values.projectName }}',
      "rules:",
      ' - apiGroups: [""]',
      '   resources: ["pods","configmaps","namespaces"]',
      '   verbs: ["create","delete","get","list","patch","update","watch"]',
      ' - apiGroups: [""]',
      '   resources: ["pods/exec"]',
      '   verbs: ["create","delete","get","list","patch","update","watch"]',
      ' - apiGroups: [""]',
      '   resources: ["pods/log"]',
      '   verbs: ["get","list","watch"]',
      "---",
      "kind: RoleBinding",
      "metadata:",
      " name: jenkins",
      "subjects:",
      " - kind: ServiceAccount",
      '   name: {{ required ".Values.roles.jenkins.serviceAccount" .Values.roles.jenkins.serviceAccount }}',
    ),
    summary: t(
      "Jenkins が Kubernetes Agent Pod を作成・監視するための RBAC テンプレートです。",
      "Jenkins 创建和监控 Kubernetes Agent Pod 所需的 RBAC 模板。",
    ),
    points: [
      t("pods / pods/exec / pods/log の権限を明示しています。", "显式配置 pods / pods/exec / pods/log 权限。"),
      t("ServiceAccount を Deployment に紐付けます。", "ServiceAccount 与 Deployment 绑定。"),
      t("必要最小限の namespace scoped Role として説明できます。", "可作为 namespace scoped 最小权限设计说明。"),
    ],
  }),
  codeFile({
    id: "aks-get-config",
    path: "JenkinsOnAKS/get-config.sh",
    language: "shell",
    code: snippet(
      "# Cosmetics for the created config",
      "read -p 'Cluster name: ' clusterName",
      "read -p 'Server address (use `kubectl cluster-info`): ' server",
      "read -p 'Namespace: ' namespace",
      "read -p 'Service account name: ' serviceAccount",
      "",
      "set -o errexit",
      "",
      "secretName=$(kubectl --namespace $namespace get serviceAccount $serviceAccount -o jsonpath='{.secrets[0].name}')",
      "ca=$(kubectl --namespace $namespace get secret/$secretName -o jsonpath='{.data.ca\\.crt}')",
      "token=$(kubectl --namespace $namespace get secret/$secretName -o jsonpath='{.data.token}' | base64 --decode)",
      "",
      "echo \"",
      "---",
      "apiVersion: v1",
      "kind: Config",
      "clusters:",
      "  - name: ${clusterName}",
      "    cluster:",
      "      certificate-authority-data: ${ca}",
      "      server: ${server}",
      "contexts:",
      "  - name: ${serviceAccount}@${clusterName}",
      "users:",
      "  - name: ${serviceAccount}",
      "    user:",
      "      token: ${token}",
      "current-context: ${serviceAccount}@${clusterName}",
      "\"",
    ),
    summary: t(
      "ServiceAccount から kubeconfig を生成し、Jenkins からクラスタ操作できるようにする補助スクリプトです。",
      "从 ServiceAccount 生成 kubeconfig，供 Jenkins 访问集群的辅助脚本。",
    ),
    points: [
      t("serviceAccount の secret から CA と token を取得します。", "从 serviceAccount 的 secret 获取 CA 与 token。"),
      t("cluster/context/user を含む kubeconfig を出力します。", "输出包含 cluster/context/user 的 kubeconfig。"),
      t("Jenkins credential に登録する設定生成として説明できます。", "可作为生成 Jenkins credential 所需配置的脚本说明。"),
    ],
  }),
  codeFile({
    id: "app-readme",
    path: "app-k8s-go/README.md",
    language: "markdown",
    code: snippet(
      "# app-k8s-go",
      "",
      "## Getting started",
      "",
      "To make it easy for you to get started with GitLab, here's a list of recommended next steps.",
      "",
      "## Add your files",
      "",
      "```",
      "cd existing_repo",
      "git remote add origin http://20.191.181.29/devops/app-k8s-go.git",
      "git branch -M main",
      "git push -uf origin main",
      "```",
      "",
      "## Test and Deploy",
      "",
      "Use the built-in continuous integration in GitLab.",
    ),
    summary: t(
      "app-k8s-go リポジトリに含まれる GitLab 初期 README です。",
      "app-k8s-go 仓库中的 GitLab 初始 README。",
    ),
    points: [
      t("リポジトリ単位の説明ファイルとしてコードブラウザに含めています。", "作为仓库级说明文件纳入代码浏览器。"),
      t("Git remote の対象が app-k8s-go であることを示します。", "展示 Git remote 指向 app-k8s-go。"),
      t("実装コードではなく、プロジェクト構成の補助資料です。", "这不是核心实现代码，而是项目结构辅助资料。"),
    ],
  }),
  codeFile({
    id: "helm-readme",
    path: "app-k8s-helm-go/README.md",
    language: "markdown",
    code: snippet(
      "# app-k8s-helm-go",
      "",
      "## Getting started",
      "",
      "To make it easy for you to get started with GitLab, here's a list of recommended next steps.",
      "",
      "## Add your files",
      "",
      "```",
      "cd existing_repo",
      "git remote add origin http://20.191.181.29/devops/app-k8s-helm-go.git",
      "git branch -M main",
      "git push -uf origin main",
      "```",
      "",
      "## Test and Deploy",
      "",
      "Use the built-in continuous integration in GitLab.",
    ),
    summary: t(
      "Helm Chart リポジトリに含まれる README です。",
      "Helm Chart 仓库中的 README 文件。",
    ),
    points: [
      t("app-k8s-helm-go が独立した release repository であることを示します。", "说明 app-k8s-helm-go 是独立的发布仓库。"),
      t("GitLab 初期テンプレート由来の内容を短く抜粋しています。", "简短展示 GitLab 初始模板内容。"),
      t("コード区では補助的な文書ファイルとして扱います。", "在代码区作为辅助文档文件处理。"),
    ],
  }),
  codeFile({
    id: "helm-helpers",
    path: "app-k8s-helm-go/templates/_helpers.tpl",
    language: "yaml",
    code: snippet(
      "{{/*",
      "Expand the name of the chart.",
      "*/}}",
      '{{- define "app-k8s-helm-go.name" -}}',
      '{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}',
      "{{- end }}",
      "",
      '{{- define "app-k8s-helm-go.fullname" -}}',
      "{{- if .Values.fullnameOverride }}",
      '{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}',
      "{{- else }}",
      "{{- $name := default .Chart.Name .Values.nameOverride }}",
      "{{- if contains $name .Release.Name }}",
      '{{- .Release.Name | trunc 63 | trimSuffix "-" }}',
      "{{- else }}",
      '{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}',
      "{{- end }}",
      "{{- end }}",
      "{{- end }}",
      "",
      '{{- define "app-k8s-helm-go.selectorLabels" -}}',
      'app.kubernetes.io/name: {{ include "app-k8s-helm-go.name" . }}',
      "app.kubernetes.io/instance: {{ .Release.Name }}",
      "{{- end }}",
      "",
      '{{- define "app-k8s-helm-go.serviceAccountName" -}}',
      "{{- if .Values.serviceAccount.create }}",
      '{{- default (include "app-k8s-helm-go.fullname" .) .Values.serviceAccount.name }}',
      "{{- else }}",
      '{{- default "default" .Values.serviceAccount.name }}',
      "{{- end }}",
      "{{- end }}",
    ),
    summary: t(
      "Chart 全体で再利用する name、fullname、labels、serviceAccountName の helper です。",
      "Chart 内复用 name、fullname、labels、serviceAccountName 的 helper。",
    ),
    points: [
      t("Kubernetes 名称の 63 文字制限を helper で吸収します。", "通过 helper 处理 Kubernetes 名称 63 字符限制。"),
      t("selectorLabels を Deployment/Service/NetworkPolicy で共通化します。", "Deployment/Service/NetworkPolicy 复用 selectorLabels。"),
      t("ServiceAccount 名を values によって切り替えます。", "ServiceAccount 名称可通过 values 切换。"),
    ],
  }),
  codeFile({
    id: "helm-serviceaccount",
    path: "app-k8s-helm-go/templates/serviceaccount.yaml",
    language: "yaml",
    code: snippet(
      "{{- if .Values.serviceAccount.create -}}",
      "apiVersion: v1",
      "kind: ServiceAccount",
      "metadata:",
      '  name: {{ include "app-k8s-helm-go.serviceAccountName" . }}',
      "  labels:",
      '    {{- include "app-k8s-helm-go.labels" . | nindent 4 }}',
      "  {{- with .Values.serviceAccount.annotations }}",
      "  annotations:",
      "    {{- toYaml . | nindent 4 }}",
      "  {{- end }}",
      "{{- end }}",
    ),
    summary: t(
      "アプリ Pod 用 ServiceAccount を必要に応じて作成する Helm テンプレートです。",
      "按需创建应用 Pod ServiceAccount 的 Helm 模板。",
    ),
    points: [
      t("serviceAccount.create で作成有無を制御します。", "通过 serviceAccount.create 控制是否创建。"),
      t("annotations を values から注入できます。", "annotations 可从 values 注入。"),
      t("Deployment の serviceAccountName と helper で接続します。", "通过 helper 与 Deployment 的 serviceAccountName 连接。"),
    ],
  }),
  codeFile({
    id: "helm-test",
    path: "app-k8s-helm-go/templates/tests/test-connection.yaml",
    language: "yaml",
    code: snippet(
      "apiVersion: v1",
      "kind: Pod",
      "metadata:",
      '  name: "{{ include "app-k8s-helm-go.fullname" . }}-test-connection"',
      "  labels:",
      '    {{- include "app-k8s-helm-go.labels" . | nindent 4 }}',
      "  annotations:",
      '    "helm.sh/hook": test',
      "spec:",
      "  containers:",
      "    - name: wget",
      "      image: busybox",
      "      command: ['wget']",
      '      args: [\'{{ include "app-k8s-helm-go.fullname" . }}:{{ .Values.service.port }}\']',
      "  restartPolicy: Never",
    ),
    summary: t(
      "helm test で Service 接続を確認する test hook Pod です。",
      "用于 helm test 验证 Service 连通性的 test hook Pod。",
    ),
    points: [
      t("helm.sh/hook=test で release 後の疎通確認に使います。", "通过 helm.sh/hook=test 用于发布后的连通性检查。"),
      t("busybox wget で Service 名と port にアクセスします。", "使用 busybox wget 访问 Service 名与端口。"),
      t("restartPolicy: Never で一回限りの検査 Pod として動作します。", "restartPolicy: Never 使其作为一次性检查 Pod。"),
    ],
  }),
  codeFile({
    id: "helm-notes",
    path: "app-k8s-helm-go/templates/NOTES.txt",
    language: "text",
    code: snippet(
      "1. Get the application URL by running these commands:",
      "{{- if .Values.ingress.enabled }}",
      "{{- range $host := .Values.ingress.hosts }}",
      "  {{- range .paths }}",
      "  http{{ if $.Values.ingress.tls }}s{{ end }}://{{ $host.host }}{{ .path }}",
      "  {{- end }}",
      "{{- end }}",
      "{{- else if contains \"NodePort\" .Values.service.type }}",
      "  export NODE_PORT=$(kubectl get --namespace {{ .Release.Namespace }} -o jsonpath=\"{.spec.ports[0].nodePort}\" services {{ include \"app-k8s-helm-go.fullname\" . }})",
      "  export NODE_IP=$(kubectl get nodes --namespace {{ .Release.Namespace }} -o jsonpath=\"{.items[0].status.addresses[0].address}\")",
      "  echo http://$NODE_IP:$NODE_PORT",
      "{{- else if contains \"ClusterIP\" .Values.service.type }}",
      "  export POD_NAME=$(kubectl get pods --namespace {{ .Release.Namespace }} -l \"app.kubernetes.io/name={{ include \"app-k8s-helm-go.name\" . }},app.kubernetes.io/instance={{ .Release.Name }}\" -o jsonpath=\"{.items[0].metadata.name}\")",
      "  kubectl --namespace {{ .Release.Namespace }} port-forward $POD_NAME 8080:$CONTAINER_PORT",
      "{{- end }}",
    ),
    summary: t(
      "Helm install 後に表示される接続案内テンプレートです。",
      "Helm install 后输出的访问说明模板。",
    ),
    points: [
      t("Ingress / NodePort / ClusterIP ごとに確認方法を切り替えます。", "按 Ingress / NodePort / ClusterIP 切换访问确认方法。"),
      t("release namespace と helper 名を使って kubectl コマンドを生成します。", "使用 release namespace 与 helper 名生成 kubectl 命令。"),
      t("運用者が install 後すぐ接続確認できる補助情報です。", "为运维人员发布后快速验证访问提供辅助信息。"),
    ],
  }),
  codeFile({
    id: "jenkinslib-readme",
    path: "app-k8s-jenkinslib/README.md",
    language: "markdown",
    code: snippet(
      "# app-k8s-jenkinslib",
      "",
      "## Getting started",
      "",
      "To make it easy for you to get started with GitLab, here's a list of recommended next steps.",
      "",
      "```",
      "cd existing_repo",
      "git remote add origin http://20.191.181.29/devops/app-k8s-jenkinslib.git",
      "git branch -M main",
      "git push -uf origin main",
      "```",
      "",
      "## Test and Deploy",
      "",
      "Use the built-in continuous integration in GitLab.",
    ),
    summary: t(
      "Jenkins Shared Library リポジトリの README です。",
      "Jenkins Shared Library 仓库的 README。",
    ),
    points: [
      t("CI/CD 共通ライブラリが独立 repository であることを示します。", "说明 CI/CD 共用库是独立仓库。"),
      t("GitLab 初期テンプレート由来の情報を短く表示します。", "简短展示 GitLab 初始模板信息。"),
      t("実装ファイルではなく、補助的なリポジトリ文書です。", "这不是实现文件，而是辅助仓库文档。"),
    ],
  }),
  codeFile({
    id: "aks-readme",
    path: "JenkinsOnAKS/README.md",
    language: "markdown",
    code: snippet(
      "# Jenkins on AKS",
      "",
      "## 環境要求",
      "- kubernetes  v1.23.0",
      "- Helm 3.0+",
      "",
      "## 本地Domain追加",
      "",
      "```",
      "IP地址加到HOST文件",
      "192.168.1.121  jenkins.cicd.com",
      "```",
      "",
      "### 安裝",
      "",
      "```",
      "helm upgrade --install --create-namespace devops-storage ./devops-storage/ -f values.yaml -n devops-apps",
      "helm upgrade --install --create-namespace devops-apps-roles ./devops-apps-roles/ -f values.yaml -n devops-apps",
      "helm upgrade --install --create-namespace devops-apps ./devops-apps/ -f values.yaml -n devops-apps",
      "helm upgrade --install --create-namespace devops-apps-route ./devops-apps-route/ -f values.yaml -n devops-apps",
      "```",
    ),
    summary: t(
      "Jenkins on AKS の前提条件と Helm install 手順をまとめた README です。",
      "Jenkins on AKS 的前置条件与 Helm install 操作说明。",
    ),
    points: [
      t("Kubernetes と Helm の前提バージョンを明記しています。", "明确 Kubernetes 与 Helm 前置版本。"),
      t("storage / roles / apps / route の分割 Chart を順に適用します。", "按 storage / roles / apps / route 顺序安装拆分 Chart。"),
      t("ローカル domain 設定も含めてデモ環境を再現できます。", "包含本地域名配置，便于复现实验环境。"),
    ],
  }),
  codeFile({
    id: "aks-apps-chart",
    path: "JenkinsOnAKS/devops-apps/Chart.yaml",
    label: "devops-apps Chart.yaml",
    language: "yaml",
    code: snippet(
      "apiVersion: v2",
      "name: devops-apps",
      "description: devops-apps",
      "type: application",
      "version: 0.1.0",
      'appVersion: "1.16.0"',
    ),
    summary: t(
      "Jenkins controller Deployment を含む devops-apps Chart のメタ情報です。",
      "包含 Jenkins controller Deployment 的 devops-apps Chart 元信息。",
    ),
    points: [
      t("Jenkins 本体の Deployment template と同じ Chart に属します。", "与 Jenkins 主体 Deployment template 属于同一 Chart。"),
      t("application Chart として install/upgrade できます。", "作为 application Chart 执行 install/upgrade。"),
      t("JenkinsOnAKS の分割 Helm 構成を示します。", "展示 JenkinsOnAKS 的拆分 Helm 结构。"),
    ],
  }),
  codeFile({
    id: "aks-storage-chart",
    path: "JenkinsOnAKS/devops-storage/Chart.yaml",
    label: "devops-storage Chart.yaml",
    language: "yaml",
    code: snippet(
      "apiVersion: v2",
      "name: devops-tools-storage",
      "description: devops-tools-storage",
      "type: application",
      "version: 0.1.0",
      'appVersion: "1.16.0"',
    ),
    summary: t(
      "Jenkins PVC を管理する storage Chart のメタ情報です。",
      "管理 Jenkins PVC 的 storage Chart 元信息。",
    ),
    points: [
      t("PVC をアプリ本体と分けて先に適用できます。", "PVC 可与应用主体分离并优先安装。"),
      t("Jenkins home の永続化責務を明確にします。", "明确 Jenkins home 持久化职责。"),
      t("README の install 順序と対応します。", "与 README 中的安装顺序对应。"),
    ],
  }),
  codeFile({
    id: "aks-route-chart",
    path: "JenkinsOnAKS/devops-apps-route/Chart.yaml",
    label: "devops-route Chart.yaml",
    language: "yaml",
    code: snippet(
      "apiVersion: v2",
      "name: devops-apps-route",
      "description: devops-apps-route",
      "type: application",
      "version: 0.1.0",
      'appVersion: "1.16.0"',
    ),
    summary: t(
      "Jenkins Service/Ingress を管理する route Chart のメタ情報です。",
      "管理 Jenkins Service/Ingress 的 route Chart 元信息。",
    ),
    points: [
      t("公開経路をアプリ本体から分離します。", "将访问入口从应用主体中拆分。"),
      t("Service と Ingress template を同じ Chart にまとめます。", "Service 与 Ingress template 归入同一 Chart。"),
      t("domain 設定は values.yaml から注入されます。", "domain 配置从 values.yaml 注入。"),
    ],
  }),
  codeFile({
    id: "aks-roles-chart",
    path: "JenkinsOnAKS/devops-apps-roles/Chart.yaml",
    label: "devops-roles Chart.yaml",
    language: "yaml",
    code: snippet(
      "apiVersion: v2",
      "name: devops-apps-roles",
      "description: devops-apps-roles",
      "type: application",
      "version: 0.1.0",
      'appVersion: "1.16.0"',
    ),
    summary: t(
      "Jenkins ServiceAccount/Role/RoleBinding を管理する RBAC Chart のメタ情報です。",
      "管理 Jenkins ServiceAccount/Role/RoleBinding 的 RBAC Chart 元信息。",
    ),
    points: [
      t("RBAC をアプリ本体から分離して先に適用できます。", "RBAC 可从应用主体中拆出并优先安装。"),
      t("Jenkins Kubernetes Agent 実行権限の境界を説明しやすくします。", "便于说明 Jenkins Kubernetes Agent 的权限边界。"),
      t("role-jenkins.yaml と同じ Chart に属します。", "与 role-jenkins.yaml 属于同一 Chart。"),
    ],
  }),
  codeFile({
    id: "portfolio-app",
    path: "portfolio-site/src/App.tsx",
    language: "tsx",
    code: snippet(
      "const showcaseRoots = [",
      '  { root: "app-k8s-helm-go", description: { ja: "アプリ配布 Chart", zh: "应用发布 Chart" } },',
      '  { root: "app-k8s-jenkinslib", description: { ja: "Pipeline 共有化", zh: "Pipeline 共享库" } },',
      '  { root: "JenkinsOnAKS", description: { ja: "Jenkins on AKS", zh: "Jenkins on AKS" } },',
      '  { root: "portfolio-site", description: { ja: "この展示サイト", zh: "本演示网站" } },',
      "] as const;",
      "",
      "const showcaseCodeFiles = showcaseCodeFileIds",
      "  .map((id) => codeFiles.find((file) => file.id === id))",
      "  .filter((file): file is CodeFile => Boolean(file));",
      "",
      "function CodeBrowser({ locale }: { locale: Locale }) {",
      "  const [activeId, setActiveId] = useState(showcaseCodeFiles[0].id);",
      "  const activeFile = useMemo(",
      "    () => showcaseCodeFiles.find((file) => file.id === activeId) ?? showcaseCodeFiles[0],",
      "    [activeId],",
      "  );",
      "  const groupedFiles = useMemo(() => groupFilesByFolder(showcaseCodeFiles), []);",
      '  const activeRoot = activeFile.path.split("/")[0];',
      "  const activeRootFiles =",
      "    groupedFiles.find((group) => group.folder === activeRoot)?.files ?? showcaseCodeFiles;",
      "  return <div className=\"code-browser-wrap\">...</div>;",
      "}",
    ),
    summary: t(
      "この React 単一ページサイトのコードブラウザ部分です。表示対象の repo を絞り、面接で話しやすい順序で見せます。",
      "本 React 单页网站的代码浏览器实现。将展示范围收敛到指定目录，并按面试说明顺序组织文件。",
    ),
    points: [
      t("showcaseRoots で左側に見せるディレクトリを固定しています。", "通过 showcaseRoots 固定左侧要展示的目录。"),
      t("showcaseCodeFileIds で重要ファイルだけを抽出し、全量表示を避けています。", "通过 showcaseCodeFileIds 只抽取关键文件，避免全量目录过散。"),
      t("選択中の root と file を同じ state で管理し、Tab とファイルツリーを同期しています。", "选中目录、Tab 与文件树共享同一状态，点击后同步切换。"),
    ],
  }),
  codeFile({
    id: "portfolio-code-data",
    path: "portfolio-site/src/codeFiles.ts",
    language: "ts",
    code: snippet(
      'import type { CodeFile, LocalizedText } from "./types";',
      "",
      'type CodeFileInput = Omit<CodeFile, "label"> & { label?: string };',
      "const t = (ja: string, zh: string): LocalizedText => ({ ja, zh });",
      'const snippet = (...lines: string[]) => lines.join("\\n");',
      "",
      "const compactLabel = (path: string) => {",
      '  const [, ...rest] = path.split("/");',
      "  if (rest.length <= 2) {",
      '    return rest.join("/") || path;',
      "  }",
      '  return rest.slice(-2).join("/");',
      "};",
      "",
      "const codeFile = ({ label, ...file }: CodeFileInput): CodeFile => ({",
      "  ...file,",
      "  label: label ?? compactLabel(file.path),",
      "});",
      "",
      "export const codeFiles: CodeFile[] = [",
      "  codeFile({",
      '    id: "helm-deployment",',
      '    path: "app-k8s-helm-go/templates/deployment.yaml",',
      '    language: "yaml",',
      "    code: snippet(\"apiVersion: apps/v1\", \"kind: Deployment\"),",
      "  }),",
      "];",
    ),
    summary: t(
      "コードブラウザに表示する実ファイル片段、説明、実装ポイントを静的データとしてまとめています。",
      "这里把代码浏览器展示的真实文件片段、说明和实现要点统一维护为静态数据。",
    ),
    points: [
      t("CodeFile 型に合わせ、path/language/code/summary/points を一つの構造にしています。", "按 CodeFile 类型统一维护 path、language、code、summary 和 points。"),
      t("snippet 関数でコード行を配列から組み立て、行番号表示と合わせやすくしています。", "用 snippet 函数按行组织代码，便于前端生成行号。"),
      t("label を自動短縮し、Tab 上で長いパスが詰まらないようにしています。", "自动生成短标签，避免 Tab 上显示过长路径。"),
    ],
  }),
  codeFile({
    id: "portfolio-styles",
    path: "portfolio-site/src/styles.css",
    language: "css",
    code: snippet(
      ".code-browser-wrap {",
      "  display: grid;",
      "  gap: 14px;",
      "}",
      "",
      ".code-scope-actions {",
      "  display: grid;",
      "  grid-template-columns: repeat(4, minmax(0, 1fr));",
      "  gap: 10px;",
      "}",
      "",
      ".code-browser {",
      "  display: grid;",
      "  grid-template-columns: 270px minmax(0, 1fr) 290px;",
      "  min-height: 438px;",
      "  overflow: hidden;",
      "}",
      "",
      "@media (max-width: 820px) {",
      "  .code-browser {",
      "    grid-template-columns: 1fr;",
      "  }",
      "",
      "  .file-tree {",
      "    max-height: 230px;",
      "  }",
      "}",
    ),
    summary: t(
      "コード区の三栏レイアウト、ディレクトリ範囲ボタン、モバイル時の縦積み表示を定義しています。",
      "定义代码区三栏布局、目录范围按钮，以及移动端纵向堆叠展示。",
    ),
    points: [
      t("desktop では file tree / code / explanation の三栏を保ちます。", "桌面端保持文件树、代码、说明三栏布局。"),
      t("scope button は 4 ディレクトリを横並びにし、表示範囲を先に伝えます。", "目录按钮横向展示 4 个目录，先告诉访客当前展示范围。"),
      t("mobile では一栏に落とし、コード区だけ横スクロールさせます。", "移动端降为单栏，只有代码内容自身可横向滚动。"),
    ],
  }),
];
